# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
#
email: stevendiaz@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  My projects live on my Github page. If you want to contact me,
  feel free to hit me up on twitter or drop me an email.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stevendiaz.net" # the base hostname & protocol for your site
twitter_username: downloadSteven
github_username:  stevendiaz
linkedin_username: steven-diaz
google analytics: UA-65559692-1
gems: [neat, bourbon, base]

# Build settings
markdown: kramdown
